// Runs before `vite dev` and `vite build` (predev/prebuild hooks); writes public/sitemap.xml.
// Keeps the sitemap in sync with static routes in src/App.tsx and dynamic content in src/content/nova.ts.

import { writeFileSync } from "fs";
import { resolve } from "path";
import { services, projects, industries, blogPosts } from "../src/content/nova";

// TODO: replace with your project URL once a project name or custom domain is set.
const BASE_URL = "";

interface SitemapEntry {
  path: string;
  lastmod?: string;
  changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority?: string;
}

const staticEntries: SitemapEntry[] = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.8" },
  { path: "/services", changefreq: "monthly", priority: "0.9" },
  { path: "/work", changefreq: "weekly", priority: "0.9" },
  { path: "/case-studies", changefreq: "weekly", priority: "0.8" },
  { path: "/industries", changefreq: "monthly", priority: "0.7" },
  { path: "/process", changefreq: "monthly", priority: "0.7" },
  { path: "/pricing", changefreq: "monthly", priority: "0.8" },
  { path: "/team", changefreq: "monthly", priority: "0.6" },
  { path: "/careers", changefreq: "weekly", priority: "0.6" },
  { path: "/blog", changefreq: "weekly", priority: "0.8" },
  { path: "/testimonials", changefreq: "monthly", priority: "0.5" },
  { path: "/contact", changefreq: "yearly", priority: "0.7" },
  { path: "/book", changefreq: "yearly", priority: "0.7" },
  { path: "/faq", changefreq: "monthly", priority: "0.6" },
  { path: "/privacy", changefreq: "yearly", priority: "0.2" },
  { path: "/terms", changefreq: "yearly", priority: "0.2" },
  { path: "/cookies", changefreq: "yearly", priority: "0.2" },
];

const dynamicEntries: SitemapEntry[] = [
  ...services.map((s) => ({ path: `/services/${s.slug}`, changefreq: "monthly" as const, priority: "0.7" })),
  ...projects.map((p) => ({ path: `/work/${p.slug}`, changefreq: "monthly" as const, priority: "0.7" })),
  ...industries.map((i) => ({ path: `/industries/${i.slug}`, changefreq: "monthly" as const, priority: "0.6" })),
  ...blogPosts.map((p) => ({
    path: `/blog/${p.slug}`,
    lastmod: p.date,
    changefreq: "monthly" as const,
    priority: "0.5",
  })),
];

// Omitted intentionally: /search (noindex), /not-found (404), any /lovable/* internal routes.
const entries: SitemapEntry[] = [...staticEntries, ...dynamicEntries];

function generateSitemap(entries: SitemapEntry[]) {
  const urls = entries.map((e) =>
    [
      `  <url>`,
      `    <loc>${BASE_URL}${e.path}</loc>`,
      e.lastmod ? `    <lastmod>${e.lastmod}</lastmod>` : null,
      e.changefreq ? `    <changefreq>${e.changefreq}</changefreq>` : null,
      e.priority ? `    <priority>${e.priority}</priority>` : null,
      `  </url>`,
    ]
      .filter(Boolean)
      .join("\n"),
  );

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Auto-generated by scripts/generate-sitemap.ts. BASE_URL is blank until a project domain is set. -->`,
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
    ...urls,
    `</urlset>`,
  ].join("\n");
}

writeFileSync(resolve("public/sitemap.xml"), generateSitemap(entries));
console.log(`sitemap.xml written (${entries.length} entries)`);
